language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23
    - extra-android-m2repository
    
before_install:
 - chmod +x gradlew
